language: rust
rust:
  - nightly
  - beta
  - stable
sudo: 9000
dist: focal
os:
  - linux
  - osx
osx_image: xcode11

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf2.13
  homebrew:
    update: true
    packages:
      - python
      - autoconf@2.13
      - ccache
      - llvm
      - yasm

env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=clang; export CXX=clang++; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYTHON3="/usr/local/opt/python/bin/python3"; fi

script:
  - ccache -z
  - CCACHE=$(which ccache) travis_wait 30 cargo build --verbose $FEATURES
  - CCACHE=$(which ccache) RUST_BACKTRACE=1 cargo test --verbose $FEATURES
  - ccache -s

cache: ccache
